filter:
  excluded_paths: [selenium/*]

build:
  nodes:
    coverage:
      tests:
        override:
          - command: npm run test:ci
            coverage:
              file: coverage/clover.xml
              format: clover
